global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['api:8000']
    tls_config:
      insecure_skip_verify: true

  - job_name: 'consumer'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['consumer:8000']
    tls_config:
      insecure_skip_verify: true

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080'] 